title: OpenAMP Project
description: >-
  OpenAMP (Open Asymmetric Multi-Processing) seeks to standardize the interactions between operating environments in a heterogeneous embedded system through open source solutions for Asymmetric MultiProcessing (AMP).
url: "https://openampproject.org"
theme: jumbo-jekyll-theme
email: contact@linaro.org
plugins:
  - jekyll-data
exclude:
  - _site
  - CODEOWNERS
  - build-site.sh
  - check-links.sh
  - Gemfile
  - Gemfile.lock
  - README.md
permalink: /:categories/:title/
blog_images_dir: assets/images/
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      comments: false
      image: /assets/images/social-media-image.png
  -
    scope:
      path: "_posts" # an empty string here means all files in the project
    values:
      layout: post
include: ['_pages']
